---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - python3-psutil

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: chrispy
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'" 

  - name: set wallpaper position
    become_user: chrispy
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: set dark mode
    become_user: chrispy
    dconf:
      key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"

  - name: terminal - set dark mode
    become_user: chrispy
    dconf:
      key: "/org/gnome/terminal/legacy/theme-variant"
      value: "'dark'"

  - name: terminal - set mnemonics enabled
    become_user: chrispy
    dconf:
      key: "/org/gnome/terminal/legacy/mnemonics-enabled"
      value: "true"
