---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux
        - python3-psutil
        - flatpak
        - gnome-software-plugin-flatpak

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: /usr/share/backgrounds/ansible-wallpaper.jpg
      owner: root
      group: root

  - name: set wallpaper
    become_user: chrispy
    dconf:
      key: "/org/gnome/desktop/background/picture-uri-dark"
      value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'" 

  - name: set wallpaper position
    become_user: chrispy
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: set dark mode
    become_user: chrispy
    dconf:
      key: "/org/gnome/desktop/interface/color-scheme"
      value: "'prefer-dark'"

  - name: terminal - set dark mode
    become_user: chrispy
    dconf:
      key: "/org/gnome/terminal/legacy/theme-variant"
      value: "'dark'"

  - name: terminal - set mnemonics enabled
    become_user: chrispy
    dconf:
      key: "/org/gnome/terminal/legacy/mnemonics-enabled"
      value: "true"

  - name: Add the flathub flatpak repository remote to the user installation
    become_user: chrispy
    community.general.flatpak_remote:
      name: flathub
      state: present
      flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
      method: user

  - name: Install the spotify flatpak
    become_user: chrispy
    community.general.flatpak:
      name: com.spotify.Client
      state: present
      method: user

  - name: Install firefox flatpak
    become_user: chrispy
    community.general.flatpak:
      name: org.mozilla.firefox
      state: present
      method: user

  - name: Install libreoffice flatpak
    become_user: chrispy
    community.general.flatpack:
      name: org.libreoffice.LibreOffice
      state: present
      method: user

